"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ShoppingCart, Clock, CheckCircle2, AlertCircle, ArrowRight, TrendingUp } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { useDailyMealSummary } from "@/lib/hooks/use-meals";
import { useLanguage } from "@/lib/hooks/use-language";
import { getTodayString, formatDate } from "@/lib/utils/date";
import { addDays } from "@/lib/utils/date-range";
import type { MessSettings } from "@/lib/types";

const MEAL_KEYS = [
  { key: "total_breakfast" as const, emoji: "🌅", tKey: "breakfast" as const },
  { key: "total_lunch" as const, emoji: "☀️", tKey: "lunch" as const },
  { key: "total_dinner" as const, emoji: "🌙", tKey: "dinner" as const },
];

interface Props {
  messSettings: Partial<MessSettings>;
  todaySummary: { total_breakfast: number; total_lunch: number; total_dinner: number } | null | undefined;
  todayLoading: boolean;
}

function getTimeLeftUntilCutoff(advanceTime: string): { hours: number; minutes: number } | null {
  const [h, m] = advanceTime.split(":").map(Number);
  const now = new Date();
  const cutoffMins = (h ?? 22) * 60 + (m ?? 0);
  const nowMins = now.getHours() * 60 + now.getMinutes();
  const remaining = cutoffMins - nowMins;
  if (remaining <= 0) return null;
  return { hours: Math.floor(remaining / 60), minutes: remaining % 60 };
}

export function TomorrowBazaarCard({ messSettings, todaySummary, todayLoading }: Props) {
  const { t } = useLanguage();
  const router = useRouter();
  const today = getTodayString();
  const tomorrow = addDays(today, 1);

  const { data: tomorrowSummary, isLoading: tomorrowLoading } = useDailyMealSummary(tomorrow);

  const cutoffDays  = messSettings.cutoff_days_before  ?? 0;
  const cutoffMode  = messSettings.cutoff_time_mode    ?? "per_meal";
  const singleTime  = messSettings.cutoff_single_time  ?? "22:00";
  // For "confirm tomorrow" check we only use single mode; per_meal each slot has own deadline.
  const advanceTime = cutoffMode === "single" ? singleTime : "22:00";

  const [timeLeft, setTimeLeft] = useState<{ hours: number; minutes: number } | null>(null);

  const isTomorrowConfirmed =
    cutoffDays > 0 &&
    cutoffMode === "single" &&
    (() => {
      const [h, m] = advanceTime.split(":").map(Number);
      const now = new Date();
      return now.getHours() * 60 + now.getMinutes() >= (h ?? 22) * 60 + (m ?? 0);
    })();

  const isSameDayMode = cutoffDays === 0;

  useEffect(() => {
    if (isTomorrowConfirmed || isSameDayMode || cutoffMode !== "single") return;
    const update = () => setTimeLeft(getTimeLeftUntilCutoff(advanceTime));
    update();
    const interval = setInterval(update, 60_000);
    return () => clearInterval(interval);
  }, [advanceTime, isTomorrowConfirmed, isSameDayMode, cutoffMode]);

  const isLoading = tomorrowLoading || todayLoading;

  const todayTotal =
    (todaySummary?.total_breakfast ?? 0) +
    (todaySummary?.total_lunch ?? 0) +
    (todaySummary?.total_dinner ?? 0);
  const tomorrowTotal =
    (tomorrowSummary?.total_breakfast ?? 0) +
    (tomorrowSummary?.total_lunch ?? 0) +
    (tomorrowSummary?.total_dinner ?? 0);

  return (
    <div className="space-y-4">
      <Card className={isTomorrowConfirmed ? "border-green-200 bg-green-50/30" : ""}>
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="text-sm font-semibold flex items-center gap-2">
              <ShoppingCart className="h-4 w-4 text-emerald-600" />
              {t.mealControl.tomorrowPlanning}
            </CardTitle>
            <Badge variant="outline" className="text-xs">
              {formatDate(tomorrow, "d MMM")}
            </Badge>
          </div>

          {isTomorrowConfirmed ? (
            <div className="flex items-start gap-2 rounded-lg bg-green-100 border border-green-200 px-3 py-2 mt-1">
              <CheckCircle2 className="h-4 w-4 text-green-600 mt-0.5 shrink-0" />
              <div>
                <p className="text-xs font-semibold text-green-700">{t.mealControl.cutoffPassedLabel}</p>
                <p className="text-xs text-green-600">{t.mealControl.dataAutoGenerated}</p>
              </div>
            </div>
          ) : isSameDayMode ? (
            <div className="flex items-start gap-2 rounded-lg bg-blue-50 border border-blue-200 px-3 py-2 mt-1">
              <AlertCircle className="h-4 w-4 text-blue-500 mt-0.5 shrink-0" />
              <p className="text-xs text-blue-700">{t.mealControl.sameDayModeNote}</p>
            </div>
          ) : (
            <div className="flex items-center justify-between rounded-lg bg-amber-50 border border-amber-200 px-3 py-2 mt-1">
              <div className="flex items-center gap-2">
                <Clock className="h-4 w-4 text-amber-600 shrink-0" />
                <div>
                  <p className="text-xs font-medium text-amber-700">{t.mealControl.cutoffPendingLabel}</p>
                  <p className="text-xs text-amber-600">{t.mealControl.cutoffTime} {advanceTime}</p>
                </div>
              </div>
              {timeLeft && (
                <span className="text-xs font-bold text-amber-700 bg-amber-100 px-2 py-1 rounded-lg">
                  {timeLeft.hours}{t.mealControl.hoursLeft} {timeLeft.minutes}{t.mealControl.minutesLeft}
                </span>
              )}
            </div>
          )}
        </CardHeader>

        <CardContent className="space-y-4">
          <div>
            <p className="text-xs font-medium text-muted-foreground mb-2">{t.mealControl.confirmedCounts}</p>
            {isLoading ? (
              <div className="grid grid-cols-3 gap-2">
                {[0, 1, 2].map((i) => <Skeleton key={i} className="h-20 rounded-xl" />)}
              </div>
            ) : (
              <div className="grid grid-cols-3 gap-2">
                {MEAL_KEYS.map(({ key, emoji, tKey }) => {
                  const count = tomorrowSummary?.[key] ?? 0;
                  return (
                    <div key={key} className={`rounded-xl p-3 text-center border ${isTomorrowConfirmed ? "bg-green-50 border-green-200" : "bg-muted/40"}`}>
                      <div className="text-xl mb-1">{emoji}</div>
                      <div className="text-lg font-bold">{count}</div>
                      <div className="text-xs text-muted-foreground">{t.meals[tKey]}</div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {isTomorrowConfirmed && (
            <Button
              onClick={() => router.push("/dashboard/bazaar")}
              className="w-full bg-emerald-600 hover:bg-emerald-700 text-white"
              size="sm"
            >
              <ShoppingCart className="h-4 w-4 mr-2" />
              {t.mealControl.goToBazaar} ({tomorrowTotal} {t.meals.personUnit})
              <ArrowRight className="h-3.5 w-3.5 ml-1" />
            </Button>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-semibold flex items-center gap-2">
            <TrendingUp className="h-4 w-4 text-purple-500" />
            {t.mealControl.comparisonTitle}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <Skeleton className="h-32 w-full rounded-xl" />
          ) : (
            <div className="overflow-hidden rounded-xl border">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-muted/50">
                    <th className="text-left px-3 py-2 text-xs font-semibold text-muted-foreground">{t.mealControl.colMeals}</th>
                    <th className="text-center px-3 py-2 text-xs font-semibold text-blue-600">{t.mealControl.today}</th>
                    <th className="text-center px-3 py-2 text-xs font-semibold text-emerald-600">{t.mealControl.tomorrow}</th>
                    <th className="text-center px-3 py-2 text-xs font-semibold text-muted-foreground">±</th>
                  </tr>
                </thead>
                <tbody>
                  {MEAL_KEYS.map(({ key, emoji, tKey }) => {
                    const todayVal = todaySummary?.[`total_${tKey}` as typeof key] ?? 0;
                    const tomorrowVal = tomorrowSummary?.[key] ?? 0;
                    const diff = tomorrowVal - todayVal;
                    return (
                      <tr key={key} className="border-t last:border-b-0">
                        <td className="px-3 py-2.5 text-xs font-medium">{emoji} {t.meals[tKey]}</td>
                        <td className="px-3 py-2.5 text-center text-sm font-bold text-blue-600">{todayVal}</td>
                        <td className="px-3 py-2.5 text-center text-sm font-bold text-emerald-600">{tomorrowVal}</td>
                        <td className={`px-3 py-2.5 text-center text-xs font-semibold ${diff > 0 ? "text-green-600" : diff < 0 ? "text-red-500" : "text-muted-foreground"}`}>
                          {diff > 0 ? `+${diff}` : diff === 0 ? "—" : diff}
                        </td>
                      </tr>
                    );
                  })}
                  <tr className="border-t bg-muted/30">
                    <td className="px-3 py-2 text-xs font-semibold">{t.mealControl.total}</td>
                    <td className="px-3 py-2 text-center text-sm font-bold text-blue-600">{todayTotal}</td>
                    <td className="px-3 py-2 text-center text-sm font-bold text-emerald-600">{tomorrowTotal}</td>
                    <td className={`px-3 py-2 text-center text-xs font-bold ${tomorrowTotal - todayTotal > 0 ? "text-green-600" : tomorrowTotal - todayTotal < 0 ? "text-red-500" : "text-muted-foreground"}`}>
                      {tomorrowTotal - todayTotal > 0 ? `+${tomorrowTotal - todayTotal}` : tomorrowTotal - todayTotal === 0 ? "—" : tomorrowTotal - todayTotal}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
